---
name: GD-SecurityImage-AC
version: 1.10
author:
  - Burak Gursoy <burak@cpan.org>
abstract: A drop-in replacement for Authen::Captcha.
license: perl
requires:
  Digest::MD5: 0
  GD::SecurityImage: 1.60
provides:
  GD::SecurityImage::AC:
    file: lib/GD/SecurityImage/AC.pm
    version: 1.10
generated_by: Module::Build version 0.2611
